staff_weights = {
    "manager_weights": {
        "Att": 3,
        "Def": 3,
        "Men": 3,
        "TCo": 3,
        "Tec": 3,
        "Youth": 1,
        "Det": 3,
        "Mot": 4,
        "Mgm": 4,
        "Judge A": 4,
        "Judge P": 3,
        "Jud SA": 3,
        "Negotiating": 3,
        "Tac Knw": 4
    },
    "assman_weights": {
        "Att": 2,
        "Def": 2,
        "Men": 2,
        "TCo": 2,
        "Tec": 2,
        "Youth": 1,
        "Det": 3,
        "Mot": 4,
        "Mgm": 4,
        "Judge A": 4,
        "Judge P": 3,
        "Jud SA": 1,
        "Negotiating": 1,
        "Tac Knw": 3
    },
    "hoyd_weights": {
        "Att": 2,
        "Def": 2,
        "Fit": 1,
        "Men": 2,
        "TCo": 2,
        "Tec": 2,
        "Youth": 4,
        "Det": 2,
        "Mot": 2,
        "Mgm": 2,
        "Judge A": 4,
        "Judge P": 4,
        "Jud SA": 3,
        "Negotiating": 2,
        "Tac Knw": 1
    },
    "coach_weights": {
        "Att": 4,
        "Def": 4,
        "Fit": 1,
        "Men": 4,
        "TCo": 4,
        "Tec": 4,
        "Youth": 1,
        "Det": 2,
        "Mot": 2,
        "Mgm": 1,
        "Judge A": 3,
        "Judge P": 3,
        "Jud SA": 1,
        "Negotiating": 1,
        "Tac Knw": 1
    },
    "fitnesscoach_weights": {
        "Fit": 4,
        "Youth": 1,
        "Det": 2,
        "Mot": 3,
        "Mgm": 2
    },
    "gkcoach_weights": {
        "Men": 2,
        "Youth": 1,
        "GkD": 4,
        "GkH": 4,
        "GkS": 4,
        "Det": 2,
        "Mot": 3,
        "Mgm": 2,
        "Judge A": 2,
        "Judge P": 2,
        "Tac Knw": 1
    },
    "setpiececoach_weights": {
        "SPC": 4,
        "TCo": 2,
        "Tec": 1,
        "Youth": 1,
        "Det": 2,
        "Mot": 2,
        "Mgm": 1
    },
    "PerfAnalyst_weights": {
        "Det": 2,
        "Judge A": 3,
        "Tac Knw": 2,
        "Ana D": 4
    },
    "dof_weights": {
        "Det": 2,
        "Mot": 2,
        "Mgm": 4,
        "Judge A": 4,
        "Judge P": 4,
        "Jud SA": 4,
        "Negotiating": 4,
        "Tac Knw": 1
    },
    "TecDir_weights": {
        "Att": 2,
        "Def": 2,
        "Fit": 1,
        "Men": 2,
        "TCo": 2,
        "Tec": 2,
        "Youth": 1,
        "Det": 2,
        "Mot": 2,
        "Mgm": 3,
        "Judge A": 3,
        "Judge P": 3,
        "Jud SA": 4,
        "Negotiating": 4,
        "Tac Knw": 1
    },
    "scout_weights": {
        "Det": 2,
        "Judge A": 4,
        "Judge P": 4,
        "Jud SA": 2,
        "Negotiating": 1,
        "Tac Knw": 4
    },
    "RecAnalyst_weights": {
        "Det": 2,
        "Judge A": 3,
        "Tac Knw": 2,
        "Ana D": 4
    },
    "LoanManager_weights": {
        "Youth": 2,
        "Det": 2,
        "Mot": 3,
        "Mgm": 4,
        "Judge A": 4,
        "Judge P": 4,
        "Tac Knw": 2
    },
    "physio_weights": {
        "Det": 2,
        "Mot": 2,
        "Mgm": 2,
        "Jud SA": 2,
        "Negotiating": 1,
        "Phy": 4,
        "SpS": 2
    },
    "sportsscience_weights": {
        "Fit": 2,
        "Det": 2,
        "Mot": 2,
        "Mgm": 2,
        "Phy": 2,
        "SpS": 4
    }
}
